title = "OWASP Coraza"
baseurl = "http://localhost/"
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
rssLimit = 10
summarylength = 20

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

copyright = "Copyright (c) 2021-2026 OWASP Coraza"

[build.buildStats]
  enable = true

[outputs]
  home = ["html", "rss", "searchIndex"]
  section = ["html", "rss"]

[outputFormats.searchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true
  notAlternative = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[caches]
  [caches.getresource]
    dir = ":cacheDir/:project"
    maxAge = -1

[taxonomies]
  contributor = "contributors"

[permalinks]
  blog = "/blog/:slug/"

[minify.tdewolff.html]
  keepComments = true
  keepWhitespace = false

[pagination]
  pagerSize = 10

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
      name = "categories"
      weight = 100
    [[related.indices]]
      name = "date"
      weight = 10

[imaging]
  anchor = "Center"
  bgColor = "#ffffff"
  hint = "photo"
  quality = 85
  resampleFilter = "Lanczos"
