# Coraza
goVersion = "1.24"

# Hugo
title = "OWASP Coraza"
description = "OWASP Coraza is an open source, enterprise-grade, high performance Web Application Firewall ready to protect your beloved applications."
images = ["cover.png"]

mainSections = ["docs"]
[social]
  twitter = "corazaio"

# Doks (@thulite/doks-core)
[doks]
  # Multilingual
  multilingualMode = true
  showMissingLanguages = true

  # Color mode
  colorMode = "auto"
  colorModeToggler = true

  # Navbar
  navbarSticky = true
  containerBreakpoint = "fluid"

  ## Button
  navBarButton = false
  navBarButtonUrl = "/docs/tutorials/quick-start/"
  navBarButtonText = "Get started"

  # FlexSearch
  flexSearch = true
  searchExclKinds = []
  searchExclTypes = []
  showSearch = []
  indexSummary = false

  ## Search results
  showDate = false
  showSummary = true
  searchLimit = 99

  # Global alert
  alert = false
  alertDismissable = true

  # Bootstrap
  bootstrapJavascript = true

  # Nav
  sectionNav = ["docs"]
  toTopButton = true
  breadcrumbTrail = false
  headlineHash = true
  scrollSpy = true

  # Versioning
  docsVersioning = false
  docsVersion = "1.0"

  # UX
  headerBar = false
  backgroundDots = true

  # Homepage
  sectionFooter = false

  # Blog
  relatedPosts = false
  imageList = true
  imageSingle = true

  # Repository
  editPage = false
  lastMod = true
  repoHost = "GitHub"
  docsRepo = "https://github.com/corazawaf/coraza"
  docsRepoBranch = "main"
  docsRepoSubPath = ""

# Debug
[render_hooks.image]
  errorLevel = 'ignore'

[render_hooks.link]
  errorLevel = 'ignore'
  highlightBroken = false

# Images (@thulite/images)
[thulite_images]
  [thulite_images.defaults]
    decoding = "async"
    fetchpriority = "auto"
    loading = "lazy"
    widths = [480, 576, 768, 1025, 1200, 1440]
    sizes = "auto"
    process = ""
    lqip = "16x webp q20"

# Inline SVG (@thulite/inline-svg)
[inline_svg]
  iconSetDir = "tabler-icons"
  iconSetVariant = "outline"

# SEO (@thulite/seo)
[seo]
  [seo.title]
    separator = " | "
    suffix = "OWASP Coraza"
  [seo.favicons]
    icon = "favicon.png"
    svgIcon = "favicon.svg"
  [seo.schemas]
    type = "Organization"
    name = "OWASP Coraza"
    sameAs = ["https://github.com/corazawaf/coraza", "https://x.com/corazaio"]
    images = ["cover.png"]
    blogPosting = ["blog"]
