name: Tests

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "LICENSE"
      - "README.md"

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: 1.25.x

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          lfs: true
          fetch-depth: 0 #for better blame info

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: '22'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2a84824a0ea66e4e5408dc63c2c86eba7e323 # v3
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Install dependencies
        run: npm install

      - name: Tests and coverage
        run: go run mage.go test

      - name: i18n content parity check
        run: go test ./tools/i18ncheck/...

      - name: Generate content
        run: go run mage.go generate

      - name: Verifies differences
        run: git diff --exit-code

      - name: Build
        run: npm run build
