name: Tests

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "LICENSE"
      - "README.md"

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: 1.26.x

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
          fetch-depth: 0 #for better blame info

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.158.0'
          extended: true

      - name: Install dependencies
        run: npm install

      - name: Tests and coverage
        run: go run mage.go test

      - name: i18n content parity check
        run: go test ./tools/i18ncheck/...

      - name: Generate content
        run: go run mage.go generate

      - name: Verifies differences
        run: git diff --exit-code

      - name: Build
        run: npm run build
